name: Build Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential

    - name: Checkout Pico SDK
      uses: actions/checkout@v3
      with:
        repository: raspberrypi/pico-sdk
        path: pico-sdk
        submodules: true

    - name: Set SDK Path
      run: echo "PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk" >> $GITHUB_ENV

    - name: Create build directory
      run: mkdir -p firmware/build

    - name: Configure CMake
      run: |
        cd firmware/build
        cmake ..

    - name: Build firmware
      run: |
        cd firmware/build
        make -j$(nproc)

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v3
      with:
        name: thumbsup-firmware
        path: firmware/build/antweight_robot.uf2
        retention-days: 30

    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: firmware/build/antweight_robot.uf2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}